# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-01 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0002_auto_20160331_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biweeklyemployee',
            name='obj_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Obj Code'),
        ),
        migrations.AlterField(
            model_name='biweeklyemployee',
            name='project_num',
            field=models.CharField(blank=True, max_length=255, verbose_name='Project #'),
        ),
        migrations.AlterField(
            model_name='biweeklyemployee',
            name='univ_id',
            field=models.CharField(max_length=9, verbose_name='University ID'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='text',
            field=models.TextField(verbose_name='Tasks'),
        ),
    ]
