# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0002_auto_20160331_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='biweeklyemployee',
            name='emails',
            field=models.BooleanField(default=True),
        ),
    ]
