# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0005_auto_20170404_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='invoiceable',
            field=models.BooleanField(default=True),
        ),
    ]
