# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 17:52
from __future__ import unicode_literals

from django.db import migrations


def invert_invoiceable(apps, schema_editor):
    # do_not_invoice => invoiceable is a change from a "falsey" to a "truthy" semantic
    # this logic works for both forwards and backwards migrations.
    Job = apps.get_model('worklog', 'Job')

    for job in Job.objects.all():
        job.invoiceable = not job.invoiceable
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0006_auto_20170404_1352'),
    ]

    operations = [
        migrations.RunPython(invert_invoiceable, invert_invoiceable),
    ]
