# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0007_invert_job_invoiceable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='do_not_invoice',
        ),
    ]
