# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0008_remove_workitem_do_not_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['name']},
        ),
    ]
